- name: Install package nvim
  become: true
  apt:
    pkg:
    - ninja-build
    - gettext
    - libtool
    - libtool-bin
    - autoconf
    - automake
    - cmake
    - g++
    - pkg-config
    - unzip
    - curl
    - doxygen
  tags:
    - install
    - neovim
    - core
