- name: Install a .deb package from the internet
  apt:
    deb: https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-linux64.deb

- name: Clone Nvchad
  ansible.builtin.git:
    repo: 'https://github.com/NvChad/NvChad'
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    depth: 1
  tags:
    - install
    - neovim
